const id = {
  "meta.title": "Bayu Andika | Portofolio Karier",
  "meta.description": "Portofolio karier Bayu Andika: pengalaman nyata di operasional, administrasi, ritel, produksi, dan dukungan teknis dasar.",
  "a11y.skip": "Lewati ke konten utama",
  "a11y.backTop": "Kembali ke bagian atas",
  "hero.role": "PORTOFOLIO",
  "hero.title": "Bukan cuma pernah kerja. Terbukti bisa beradaptasi.",
  "hero.lines": "BUKAN CUMA|PERNAH KERJA.|TERBUKTI BISA|BERADAPTASI.",
  "hero.description": "Empat lingkungan kerja yang berbeda membentuk satu standar kerja: cepat memahami tugas, tertib menjalankan proses, dan bertanggung jawab menyelesaikannya.",
  "hero.signal": "4 LINGKUNGAN KERJA · 1 STANDAR KERJA",
  "hero.scan": "RITEL|ADMINISTRASI|PRODUKSI|DUKUNGAN IT",
  "hero.proofStrip": "4 lingkungan kerja|Operasional|Administrasi|Ritel|Teknis",
  "hero.scrollPrompt": "Scroll untuk membuka bukti",
  "hero.experienceAction": "Buka bukti kerja",
  "common.downloadCv": "Unduh CV",
  "scan.label": "PEMBACAAN 20 DETIK",
  "scan.title": "Pengalamannya berbeda. Standar kerjanya tetap sama.",
  "scan.description": "Saya tidak membawa satu jabatan ke semua tempat. Saya membawa cara kerja yang dapat dipakai di berbagai situasi.",
  "scan.points": "Cepat memahami tugas dan lingkungan baru|Menjaga proses, data, dan hasil tetap tertib|Menyelesaikan pekerjaan dengan tanggung jawab",
  "scan.marquee": "ADAPTASI · PROSES · TANGGUNG JAWAB · BUKTI KERJA · ",
  "proof.label": "BUKTI KERJA",
  "proof.unlocked": "KEMAMPUAN TERBUKA",
  "proof.proven": "TERBUKTI",
  "profile.label": "PROFIL PROFESIONAL",
  "profile.title": "Pemahaman teknis. Disiplin operasional.",
  "profile.bridge": "Empat lingkungan kerja. Satu cara kerja yang konsisten.",
  "profile.description": "Saya terbiasa bekerja di lingkungan yang membutuhkan ketelitian, kemampuan beradaptasi, dan tanggung jawab. Mulai dari menangani perangkat, mengikuti standar produksi, mengelola data servis, sampai melayani pelanggan, saya belajar menjaga setiap pekerjaan tetap rapi, jelas, dan dapat dipertanggungjawabkan.",
  "profile.technical.title": "Dukungan Teknis",
  "profile.technical.body": "Perangkat keras, instalasi sistem operasi, dan penanganan masalah dasar.",
  "profile.process.title": "Proses & Kualitas",
  "profile.process.body": "Kepatuhan terhadap SOP, kontrol proses, dan perhatian terhadap kualitas.",
  "profile.service.title": "Pelayanan & Data",
  "profile.service.body": "Administrasi, operasional POS, dan pelayanan pelanggan.",
  "bridge.label": "PERJALANAN KERJA",
  "bridge.title": "Empat tempat kerja. Empat kemampuan yang terbentuk.",
  "bridge.description": "Setiap langkah memberi jenis bukti yang berbeda. Ikuti jalurnya untuk melihat apa yang benar-benar saya kerjakan dan kemampuan yang terbentuk setelahnya.",
  "bridge.retail": "Ritel",
  "bridge.admin": "Administrasi",
  "bridge.production": "Produksi",
  "bridge.technical": "Teknis",
  "decision.indomaret": "Adaptasi",
  "decision.bmc": "Ketelitian",
  "decision.mitra": "Disiplin",
  "decision.restu": "Problem Solving",
  "experience.label": "PENGALAMAN KERJA",
  "experience.title": "Terbentuk dari Pekerjaan Nyata.",
  "experience.intro": "Setiap pekerjaan memberi saya pengalaman yang berbeda, tetapi semuanya membentuk cara kerja yang sama: memahami tugas dengan cepat, mengikuti proses dengan benar, dan menyelesaikan pekerjaan secara bertanggung jawab.",
  "experience.indomaret.role": "Pramuniaga",
  "experience.indomaret.period": "Feb 2025 - Feb 2026",
  "experience.indomaret.body": "Dalam operasional toko yang aktif, prioritas dapat berpindah antara barang datang, kondisi rak, transaksi, dan kebutuhan pelanggan. Saya memeriksa penerimaan barang, menata stok dengan FIFO/FEFO, mengecek produk, lalu menjalankan kasir dan pelayanan sesuai kebutuhan. Hasilnya, barang, transaksi, dan pelayanan tetap tertangani secara tertib meski ritme kerja berubah cepat.",
  "experience.indomaret.kicker": "BUKTI 01 · RITEL YANG AKTIF",
  "experience.indomaret.question": "Bisa tetap akurat ketika toko bergerak cepat?",
  "experience.indomaret.proof": "Penerimaan barang|Pengecekan produk|FIFO/FEFO dan stok|Kasir & POS|Pelayanan pelanggan",
  "experience.indomaret.payoff": "Bukti utamanya: mampu mengatur prioritas tanpa melepas ketelitian pada stok, transaksi, dan pelanggan.",
  "experience.indomaret.unlock": "Ketelitian dalam ritme kerja cepat",
  "experience.bmc.role": "Admin",
  "experience.bmc.period": "Nov 2024 - Jan 2025",
  "experience.bmc.body": "Di bengkel, dokumen servis, faktur, catatan transaksi, dan pertanyaan pelanggan harus tetap saling sesuai. Saya mencatat dan mengarsipkan data servis, menyiapkan faktur, serta menyampaikan informasi biaya, waktu pengerjaan, dan ketersediaan suku cadang secara jelas. Hasilnya, informasi lebih mudah diperiksa dan alur administrasi tetap tertata.",
  "experience.bmc.kicker": "BUKTI 02 · INFORMASI MENJADI TERATUR",
  "experience.bmc.question": "Bisa menjaga data sekaligus menjelaskan informasi ke pelanggan?",
  "experience.bmc.proof": "Dokumen servis|Faktur|Pencatatan transaksi|Informasi biaya & waktu|Ketersediaan suku cadang",
  "experience.bmc.payoff": "Bukti utamanya: mampu menjaga data tetap tertib sekaligus memberi informasi yang mudah dipahami pelanggan.",
  "experience.bmc.unlock": "Kontrol data dan komunikasi yang jelas",
  "experience.mitra.role": "Operator Produksi",
  "experience.mitra.period": "Jan 2023 - Agu 2024",
  "experience.mitra.body": "Dalam proses stamping, pekerjaan harus mengikuti pengarahan, target, SOP, standar kualitas, dan K3. Saya mengoperasikan mesin press stamping, memeriksa hasil produksi, mengontrol material, menjaga area kerja, dan mencatat hasil pekerjaan. Hasilnya, proses dapat dijalankan dengan aman, konsisten, dan siap dipertanggungjawabkan.",
  "experience.mitra.kicker": "BUKTI 03 · PROSES DI BAWAH STANDAR",
  "experience.mitra.question": "Bisa konsisten di bawah SOP dan standar kualitas?",
  "experience.mitra.proof": "Mengikuti pengarahan|Menjalankan SOP|Menjaga standar kualitas|Merawat kebersihan area|Menyusun laporan tepat",
  "experience.mitra.payoff": "Bukti utamanya: mampu menjaga proses, kualitas, dan keselamatan tetap berjalan dalam standar produksi.",
  "experience.mitra.unlock": "Disiplin proses dan kesadaran kualitas",
  "experience.restu.role": "PKL / Magang Dukungan IT",
  "experience.restu.period": "Nov 2021 - Feb 2022",
  "experience.restu.body": "Saat perangkat masuk dengan masalah berbeda, penanganan tidak bisa dilakukan dengan menebak. Dalam masa PKL, saya memeriksa kondisi laptop atau PC, membongkar dan memasang komponen, meningkatkan perangkat keras, serta memasang ulang sistem operasi dan perangkat lunak. Setiap pekerjaan dilakukan bertahap sampai perangkat siap diuji kembali, membentuk kebiasaan penanganan masalah yang runtut.",
  "experience.restu.kicker": "BUKTI 04 · FONDASI TEKNIS",
  "experience.restu.question": "Bisa memahami perangkat lewat praktik langsung?",
  "experience.restu.proof": "Periksa perangkat|Bongkar dan pasang komponen|Tingkatkan perangkat keras|Pasang sistem & perangkat lunak|Tangani masalah dasar",
  "experience.restu.payoff": "Bukti utamanya: mampu menangani perangkat melalui urutan pemeriksaan, tindakan, dan pengujian kembali yang jelas.",
  "experience.restu.unlock": "Dasar teknis dan pemecahan masalah terstruktur",
  "skills.label": "KOMPETENSI",
  "skills.title": "Kemampuan yang Terbentuk melalui Praktik.",
  "skills.intro": "Kemampuan ini terbentuk dari pekerjaan yang benar-benar saya jalankan, mulai dari menangani perangkat, menjaga proses produksi, mengelola data, hingga melayani kebutuhan pelanggan.",
  "skills.technical.title": "Dukungan Teknis",
  "skills.technical.items": "Perakitan dan pembongkaran laptop atau PC|Instalasi sistem operasi dan perangkat lunak|Peningkatan komponen perangkat keras|Penanganan masalah dasar pada perangkat",
  "skills.technical.source": "TERBENTUK DI · RESTU COMPUTER",
  "skills.operations.title": "Operasional & Kualitas",
  "skills.operations.items": "Pengoperasian mesin pres stamping|Menjalankan pekerjaan sesuai SOP|Pengecekan kualitas hasil produksi|Pencatatan dan pelaporan pekerjaan",
  "skills.operations.source": "TERBENTUK DI · MITRAMETAL",
  "skills.admin.title": "Administrasi & Pelayanan",
  "skills.admin.items": "Pengelolaan data dan dokumen servis|Pembuatan dan pengarsipan faktur|Pencatatan transaksi|Komunikasi dan pelayanan pelanggan",
  "skills.admin.source": "TERBENTUK DI · BMC MOTOR",
  "skills.retail.title": "Ritel & Persediaan",
  "skills.retail.items": "Operasional kasir dan POS|Penerimaan dan pengecekan barang|FIFO/FEFO dan pengelolaan stok|Penataan, perapihan tampilan, dan planogram",
  "skills.retail.source": "TERBENTUK DI · INDOMARET",
  "capability.label": "PUSAT KENDALI KEMAMPUAN",
  "capability.system": "SISTEM_KEMAMPUAN",
  "capability.online": "AKTIF",
  "capability.title": "Empat kemampuan. Satu tempat untuk memeriksa buktinya.",
  "capability.intro": "Pilih kemampuan untuk melihat dari mana kemampuan itu terbentuk dan pekerjaan nyata yang mendukungnya.",
  "capability.status": "TERBUKTI LEWAT PEKERJAAN",
  "capability.announcement": "Kemampuan aktif: {capability}.",
  "verdict.label": "KESIMPULAN UNTUK PEREKRUT",
  "verdict.title": "Cepat memahami. Tertib menjalankan. Bertanggung jawab menyelesaikan.",
  "verdict.description": "Saya siap membawa standar kerja tersebut ke peran berikutnya dan mempelajari kebutuhan baru dengan serius.",
  "verdict.action": "MARI BICARA",
  "education.label": "PENDIDIKAN",
  "education.title": "Awal dari Dasar Kemampuan Teknis.",
  "education.institution": "SMK Muhammadiyah 1 Muntilan",
  "education.official": "Nama resmi institusi: SMK Muhammadiyah 1 Muntilan",
  "education.program": "Rekayasa Perangkat Lunak",
  "education.period": "Juli 2019 sampai Juni 2022",
  "education.description": "Jurusan Rekayasa Perangkat Lunak menjadi awal saya mengenal komputer dan teknologi. Selama sekolah, saya belajar memahami masalah secara terstruktur dan menyelesaikannya melalui langkah yang jelas. Dasar tersebut kemudian saya kembangkan melalui pengalaman praktik sebagai dukungan IT.",
  "contact.label": "SIAP BERKONTRIBUSI",
  "contact.title": "Mari Membicarakan Kesempatan Berikutnya.",
  "contact.description": "Saya terbuka untuk peluang kerja yang sesuai dengan pengalaman dan kemampuan saya. Jika profil saya sesuai dengan kebutuhan perusahaan, saya siap berdiskusi lebih lanjut mengenai posisi dan tanggung jawab yang tersedia.",
  "contact.emailAction": "Kirim Email",
  "contact.emailLabel": "Email",
  "contact.phoneLabel": "Telepon",
  "contact.linkedinLabel": "LinkedIn",
  "contact.githubLabel": "GitHub",
  "contact.instagramLabel": "Instagram",
  "contact.facebookLabel": "Facebook",
  "contact.locationLabel": "Lokasi",
  "preferences.language": "Pilihan bahasa",
  "preferences.appearance": "Pilihan tampilan",
  "preferences.id": "Bahasa Indonesia",
  "preferences.eng": "Bahasa Inggris",
  "preferences.light": "Mode terang",
  "preferences.dark": "Mode gelap",
  "footer.role": "Operasional · Administrasi · Ritel · Dukungan Teknis",
  "announce.id": "Bahasa halaman diubah ke Indonesia.",
  "announce.en": "Bahasa halaman diubah ke Inggris.",
  "announce.light": "Mode terang diaktifkan.",
  "announce.dark": "Mode gelap diaktifkan.",
};

const en = {
  "meta.title": "Bayu Andika | Career Portfolio",
  "meta.description": "Career portfolio of Bayu Andika: real experience in operations, administration, retail, production, and entry-level technical support.",
  "a11y.skip": "Skip to main content",
  "a11y.backTop": "Back to the top",
  "hero.role": "PORTFOLIO",
  "hero.title": "Not just work experience. Proven adaptability.",
  "hero.lines": "NOT JUST|WORK EXPERIENCE.|PROVEN|ADAPTABILITY.",
  "hero.description": "Four different work environments shaped one work standard: understand tasks quickly, follow the process carefully, and finish responsibly.",
  "hero.signal": "4 WORK ENVIRONMENTS · 1 WORK STANDARD",
  "hero.scan": "RETAIL|ADMINISTRATION|PRODUCTION|IT SUPPORT",
  "hero.proofStrip": "4 work environments|Operations|Administration|Retail|Technical",
  "hero.scrollPrompt": "Scroll to reveal proof",
  "hero.experienceAction": "Open work proof",
  "common.downloadCv": "Download CV",
  "scan.label": "20-SECOND SCAN",
  "scan.title": "Different experience. The same work standard.",
  "scan.description": "I do not bring one job title into every workplace. I bring a way of working that transfers across situations.",
  "scan.points": "Understand new tasks and environments quickly|Keep processes, data, and outcomes in order|Complete work with accountability",
  "scan.marquee": "ADAPTABILITY · PROCESS · ACCOUNTABILITY · WORK PROOF · ",
  "proof.label": "WORK PROOF",
  "proof.unlocked": "CAPABILITY UNLOCKED",
  "proof.proven": "PROVEN",
  "profile.label": "PROFESSIONAL PROFILE",
  "profile.title": "Technical awareness. Operational discipline.",
  "profile.bridge": "Four work environments. One consistent way of working.",
  "profile.description": "I am used to working in environments that require accuracy, adaptability, and responsibility. From handling devices and following production standards to managing service data and supporting customers, I have learned to keep every task organized, clear, and accountable.",
  "profile.technical.title": "Technical Support",
  "profile.technical.body": "Hardware, OS installation, and basic troubleshooting.",
  "profile.process.title": "Process & Quality",
  "profile.process.body": "SOP compliance, production control, and quality awareness.",
  "profile.service.title": "Service & Data",
  "profile.service.body": "Administration, POS operations, and customer support.",
  "bridge.label": "WORK JOURNEY",
  "bridge.title": "Four workplaces. Four capabilities built through work.",
  "bridge.description": "Every step carries a different kind of proof. Follow the route to see what I handled directly and the capability that stayed with me afterwards.",
  "bridge.retail": "Retail",
  "bridge.admin": "Administration",
  "bridge.production": "Production",
  "bridge.technical": "Technical",
  "decision.indomaret": "Adaptability",
  "decision.bmc": "Accuracy",
  "decision.mitra": "Discipline",
  "decision.restu": "Problem Solving",
  "experience.label": "WORK EXPERIENCE",
  "experience.title": "Experience shaped by real work.",
  "experience.intro": "Each role gave me a different kind of experience, but all of them shaped the same work ethic: understand the task quickly, follow the process correctly, and complete the work responsibly.",
  "experience.indomaret.role": "Store Crew",
  "experience.indomaret.period": "Feb 2025 - Feb 2026",
  "experience.indomaret.body": "In an active store, priorities can shift between incoming goods, shelf conditions, transactions, and customer needs. I checked deliveries, organized stock using FIFO/FEFO, inspected products, and handled cashier and service duties as needed. As a result, goods, transactions, and customer service remained orderly even when the work pace changed quickly.",
  "experience.indomaret.kicker": "PROOF 01 · ACTIVE RETAIL",
  "experience.indomaret.question": "Can he stay accurate when the store moves fast?",
  "experience.indomaret.proof": "Goods receiving|Product checks|FIFO/FEFO and stock|Cashier & POS|Customer service",
  "experience.indomaret.payoff": "The proof: I can adjust priorities without losing accuracy across stock, transactions, and customer service.",
  "experience.indomaret.unlock": "Accuracy in a fast-moving workplace",
  "experience.bmc.role": "Administrator",
  "experience.bmc.period": "Nov 2024 - Jan 2025",
  "experience.bmc.body": "At the workshop, service documents, invoices, transaction records, and customer questions had to remain consistent. I recorded and filed service data, prepared invoices, and clearly explained costs, service times, and spare-part availability. As a result, information was easier to verify and the administrative flow stayed organized.",
  "experience.bmc.kicker": "PROOF 02 · INFORMATION IN ORDER",
  "experience.bmc.question": "Can he control data while explaining information to customers?",
  "experience.bmc.proof": "Service documents|Invoices|Transaction records|Cost & time information|Spare-part availability",
  "experience.bmc.payoff": "The proof: I can keep data organized while giving customers information that is easy to understand.",
  "experience.bmc.unlock": "Data control and clear communication",
  "experience.mitra.role": "Production Operator",
  "experience.mitra.period": "Jan 2023 - Aug 2024",
  "experience.mitra.body": "Stamping work had to follow briefings, targets, SOP, quality standards, and workplace safety requirements. I operated a stamping press, inspected production output, controlled materials, maintained the work area, and recorded the results. As a result, the process could be carried out safely, consistently, and accountably.",
  "experience.mitra.kicker": "PROOF 03 · PROCESS UNDER STANDARDS",
  "experience.mitra.question": "Can he stay consistent under SOP and quality standards?",
  "experience.mitra.proof": "Follow briefings|Work to SOP|Maintain quality standards|Keep the area clean|Prepare accurate reports",
  "experience.mitra.payoff": "The proof: I can keep process, quality, and safety aligned with production standards.",
  "experience.mitra.unlock": "Process discipline and quality awareness",
  "experience.restu.role": "IT Support Intern",
  "experience.restu.period": "Nov 2021 - Feb 2022",
  "experience.restu.body": "When devices arrived with different issues, the work could not rely on guesswork. During my internship, I inspected laptops and PCs, disassembled and installed components, upgraded hardware, and reinstalled operating systems and software. Each task followed a clear sequence until the device was ready to be tested again, building a structured troubleshooting habit.",
  "experience.restu.kicker": "PROOF 04 · TECHNICAL FOUNDATION",
  "experience.restu.question": "Can he understand devices through hands-on practice?",
  "experience.restu.proof": "Inspect devices|Disassemble and assemble components|Upgrade hardware|Install OS & software|Handle basic issues",
  "experience.restu.payoff": "The proof: I can handle devices through a clear sequence of inspection, action, and retesting.",
  "experience.restu.unlock": "Technical foundation and structured problem solving",
  "skills.label": "COMPETENCIES",
  "skills.title": "Skills built through practice.",
  "skills.intro": "These skills were developed through work I have handled directly, from supporting devices and production processes to managing data and serving customers.",
  "skills.technical.title": "Technical Support",
  "skills.technical.items": "Laptop and PC assembly or disassembly|Operating-system and software installation|Hardware upgrades|Basic device troubleshooting",
  "skills.technical.source": "BUILT AT · RESTU COMPUTER",
  "skills.operations.title": "Operations & Quality",
  "skills.operations.items": "Stamping-press operation|Work according to SOP|Production-quality checks|Work records and reports",
  "skills.operations.source": "BUILT AT · MITRAMETAL",
  "skills.admin.title": "Administration & Service",
  "skills.admin.items": "Service data and document management|Invoice creation and filing|Transaction recording|Customer communication and service",
  "skills.admin.source": "BUILT AT · BMC MOTOR",
  "skills.retail.title": "Retail & Inventory",
  "skills.retail.items": "Cashier and POS operation|Receiving and checking goods|FIFO/FEFO and stock management|Display, facing, and planogram",
  "skills.retail.source": "BUILT AT · INDOMARET",
  "capability.label": "CAPABILITY COMMAND CENTER",
  "capability.system": "BAYU_CAPABILITY_OS",
  "capability.online": "ONLINE",
  "capability.title": "Four capabilities. One place to inspect the proof.",
  "capability.intro": "Choose a capability to see where it was built and the real tasks supporting it.",
  "capability.status": "PROVEN THROUGH WORK",
  "capability.announcement": "Active capability: {capability}.",
  "verdict.label": "RECRUITER VERDICT",
  "verdict.title": "Understand quickly. Execute carefully. Finish responsibly.",
  "verdict.description": "I am ready to bring that work standard into the next role and seriously learn its new requirements.",
  "verdict.action": "LET’S TALK",
  "education.label": "EDUCATION",
  "education.title": "Where the technical foundation began.",
  "education.institution": "Muhammadiyah 1 Vocational High School, Muntilan",
  "education.official": "Official institution name: SMK Muhammadiyah 1 Muntilan",
  "education.program": "Software Engineering",
  "education.period": "July 2019 to June 2022",
  "education.description": "Studying Software Engineering was where I first became familiar with computers and technology. I learned to understand problems in a structured way and solve them through clear steps. I later developed this foundation through practical experience as an IT Support intern.",
  "contact.label": "READY TO CONTRIBUTE",
  "contact.title": "Let’s Discuss the Next Opportunity.",
  "contact.description": "I am open to opportunities that match my experience and abilities. If my profile fits your company's needs, I would be glad to discuss the available role and responsibilities further.",
  "contact.emailAction": "Send Email",
  "contact.emailLabel": "Email",
  "contact.phoneLabel": "Phone",
  "contact.linkedinLabel": "LinkedIn",
  "contact.githubLabel": "GitHub",
  "contact.instagramLabel": "Instagram",
  "contact.facebookLabel": "Facebook",
  "contact.locationLabel": "Location",
  "preferences.language": "Language selection",
  "preferences.appearance": "Appearance selection",
  "preferences.id": "Indonesian language",
  "preferences.eng": "English language",
  "preferences.light": "Light mode",
  "preferences.dark": "Dark mode",
  "footer.role": "Operations · Administration · Retail · Technical Support",
  "announce.id": "Page language changed to Indonesian.",
  "announce.en": "Page language changed to English.",
  "announce.light": "Light mode enabled.",
  "announce.dark": "Dark mode enabled.",
};

export const CONTENT = Object.freeze({ id: Object.freeze(id), en: Object.freeze(en) });

export const LINKS = Object.freeze({
  email: "mailto:bayuandk4@gmail.com",
  phone: "tel:+6287881820662",
  linkedin: "https://linkedin.com/in/bayu-andika2003/",
  github: "https://github.com/bayz-dik/V-Forge",
  instagram: "https://www.instagram.com/bayydka?igsh=eGtocG5pbTJjNGcz",
  facebook: "https://www.facebook.com/share/1dEpojdwUy/",
  maps: "https://maps.app.goo.gl/4G2zN1NASnfHMoBH9",
});
