const id = {
  "meta.title": "Bayu Andika | Portofolio Karier",
  "meta.description": "Portofolio karier Bayu Andika, Spesialis Dukungan IT & Operasional.",
  "a11y.skip": "Lewati ke konten utama",
  "a11y.backTop": "Kembali ke bagian atas",
  "hero.role": "PORTOFOLIO",
  "hero.title": "Dibentuk oleh Pengalaman Operasional Nyata.",
  "hero.lines": "Dibentuk oleh|Pengalaman Operasional|Nyata.",
  "hero.description": "Saya terbiasa bekerja langsung dengan perangkat, proses, data, dan pelanggan. Pengalaman di bidang dukungan IT, produksi, administrasi, dan ritel membentuk cara kerja saya menjadi lebih teliti, adaptif, dan bertanggung jawab.",
  "hero.experienceAction": "Tinjau pengalaman kerja",
  "common.downloadCv": "Unduh CV",
  "profile.label": "PROFIL PROFESIONAL",
  "profile.title": "Pemahaman teknis. Disiplin operasional.",
  "profile.bridge": "Empat lingkungan kerja. Satu cara kerja yang konsisten.",
  "profile.description": "Saya terbiasa bekerja di lingkungan yang membutuhkan ketelitian, kemampuan beradaptasi, dan tanggung jawab. Mulai dari menangani perangkat, mengikuti standar produksi, mengelola data servis, sampai melayani pelanggan, saya belajar menjaga setiap pekerjaan tetap rapi, jelas, dan dapat dipertanggungjawabkan.",
  "profile.technical.title": "Dukungan Teknis",
  "profile.technical.body": "Perangkat keras, instalasi sistem operasi, dan penanganan masalah dasar.",
  "profile.process.title": "Proses & Kualitas",
  "profile.process.body": "Kepatuhan terhadap SOP, kontrol proses, dan perhatian terhadap kualitas.",
  "profile.service.title": "Pelayanan & Data",
  "profile.service.body": "Administrasi, operasional POS, dan pelayanan pelanggan.",
  "experience.label": "PENGALAMAN KERJA",
  "experience.title": "Terbentuk dari Pekerjaan Nyata.",
  "experience.intro": "Setiap pekerjaan memberi saya pengalaman yang berbeda, tetapi semuanya membentuk cara kerja yang sama: memahami tugas dengan cepat, mengikuti proses dengan benar, dan menyelesaikan pekerjaan secara bertanggung jawab.",
  "experience.indomaret.role": "Pramuniaga",
  "experience.indomaret.period": "Feb 2025 - Feb 2026",
  "experience.indomaret.body": "Menangani kegiatan toko dari penerimaan barang, penataan stok, pengecekan kondisi produk, hingga transaksi kasir. Pekerjaan ini melatih saya untuk tetap teliti saat bekerja dengan barang dan transaksi, cepat menyesuaikan prioritas, serta memberikan pelayanan yang baik dalam situasi kerja yang aktif.",
  "experience.bmc.role": "Admin",
  "experience.bmc.period": "Nov 2024 - Jan 2025",
  "experience.bmc.body": "Mengelola dokumen servis, faktur, dan pencatatan transaksi sekaligus membantu pelanggan mendapatkan informasi yang jelas mengenai biaya, waktu pengerjaan, dan ketersediaan suku cadang. Peran ini menguatkan kemampuan saya dalam mengelola data, berkomunikasi, dan menjaga alur administrasi tetap teratur.",
  "experience.mitra.role": "Operator Produksi",
  "experience.mitra.period": "Jan 2023 - Agu 2024",
  "experience.mitra.body": "Bekerja mengikuti pengarahan, SOP, dan standar kualitas yang berlaku dalam proses produksi. Saya terbiasa menjaga ketelitian hasil kerja, kebersihan area, dan ketepatan laporan. Pengalaman ini membentuk kedisiplinan serta kebiasaan untuk bekerja dengan aman, konsisten, dan bertanggung jawab.",
  "experience.restu.role": "Magang Dukungan IT",
  "experience.restu.period": "Nov 2021 - Feb 2022",
  "experience.restu.body": "Menangani pembongkaran dan pemasangan komponen laptop maupun PC, peningkatan perangkat keras, serta instalasi ulang sistem operasi dan perangkat lunak. Pengalaman langsung ini menjadi dasar kemampuan saya dalam memahami perangkat, mencari sumber masalah, dan melakukan perbaikan teknis secara runtut.",
  "skills.label": "KOMPETENSI",
  "skills.title": "Kemampuan yang Terbentuk melalui Praktik.",
  "skills.intro": "Kemampuan ini terbentuk dari pekerjaan yang benar-benar saya jalankan, mulai dari menangani perangkat, menjaga proses produksi, mengelola data, hingga melayani kebutuhan pelanggan.",
  "skills.technical.title": "Dukungan Teknis",
  "skills.technical.items": "Perakitan dan pembongkaran laptop atau PC|Instalasi sistem operasi dan perangkat lunak|Peningkatan komponen perangkat keras|Penanganan masalah dasar pada perangkat",
  "skills.operations.title": "Operasional & Kualitas",
  "skills.operations.items": "Pengoperasian mesin pres stamping|Menjalankan pekerjaan sesuai SOP|Pengecekan kualitas hasil produksi|Pencatatan dan pelaporan pekerjaan",
  "skills.admin.title": "Administrasi & Pelayanan",
  "skills.admin.items": "Pengelolaan data dan dokumen servis|Pembuatan dan pengarsipan faktur|Pencatatan transaksi|Komunikasi dan pelayanan pelanggan",
  "skills.retail.title": "Ritel & Persediaan",
  "skills.retail.items": "Operasional kasir dan POS|Penerimaan dan pengecekan barang|FIFO/FEFO dan pengelolaan stok|Penataan, perapihan tampilan, dan planogram",
  "education.label": "PENDIDIKAN",
  "education.title": "Awal dari Dasar Kemampuan Teknis.",
  "education.institution": "SMK Muhammadiyah 1 Muntilan",
  "education.official": "Nama resmi institusi: SMK Muhammadiyah 1 Muntilan",
  "education.program": "Rekayasa Perangkat Lunak",
  "education.period": "Juli 2019 sampai Juni 2022",
  "education.description": "Jurusan Rekayasa Perangkat Lunak menjadi awal saya mengenal komputer dan teknologi. Selama sekolah, saya belajar memahami masalah secara terstruktur dan menyelesaikannya melalui langkah yang jelas. Dasar tersebut kemudian saya kembangkan melalui pengalaman praktik sebagai dukungan IT.",
  "contact.label": "SIAP BERKONTRIBUSI",
  "contact.title": "Mari Membicarakan Kesempatan Berikutnya.",
  "contact.description": "Saya terbuka untuk peluang kerja yang sesuai dengan pengalaman dan kemampuan saya. Jika profil saya sesuai dengan kebutuhan perusahaan, saya siap berdiskusi lebih lanjut mengenai posisi dan tanggung jawab yang tersedia.",
  "contact.emailAction": "Kirim Email",
  "contact.emailLabel": "Email",
  "contact.phoneLabel": "Telepon",
  "contact.linkedinLabel": "LinkedIn",
  "contact.githubLabel": "GitHub",
  "contact.instagramLabel": "Instagram",
  "contact.facebookLabel": "Facebook",
  "contact.locationLabel": "Lokasi",
  "preferences.language": "Pilihan bahasa",
  "preferences.appearance": "Pilihan tampilan",
  "preferences.id": "Bahasa Indonesia",
  "preferences.eng": "Bahasa Inggris",
  "preferences.light": "Mode terang",
  "preferences.dark": "Mode gelap",
  "footer.role": "Spesialis Dukungan IT & Operasional",
  "announce.id": "Bahasa halaman diubah ke Indonesia.",
  "announce.en": "Bahasa halaman diubah ke Inggris.",
  "announce.light": "Mode terang diaktifkan.",
  "announce.dark": "Mode gelap diaktifkan.",
};

const en = {
  "meta.title": "Bayu Andika | Career Portfolio",
  "meta.description": "Career portfolio of Bayu Andika, IT Support & Operations Specialist.",
  "a11y.skip": "Skip to main content",
  "a11y.backTop": "Back to the top",
  "hero.role": "PORTFOLIO",
  "hero.title": "Built Across Real Operations.",
  "hero.lines": "Built Across|Real Operations.",
  "hero.description": "I am used to working directly with devices, processes, data, and customers. My experience in IT support, production, administration, and retail has shaped me into a more accurate, adaptable, and responsible professional.",
  "hero.experienceAction": "Review work experience",
  "common.downloadCv": "Download CV",
  "profile.label": "PROFESSIONAL PROFILE",
  "profile.title": "Technical awareness. Operational discipline.",
  "profile.bridge": "Four work environments. One consistent way of working.",
  "profile.description": "I am used to working in environments that require accuracy, adaptability, and responsibility. From handling devices and following production standards to managing service data and supporting customers, I have learned to keep every task organized, clear, and accountable.",
  "profile.technical.title": "Technical Support",
  "profile.technical.body": "Hardware, OS installation, and basic troubleshooting.",
  "profile.process.title": "Process & Quality",
  "profile.process.body": "SOP compliance, production control, and quality awareness.",
  "profile.service.title": "Service & Data",
  "profile.service.body": "Administration, POS operations, and customer support.",
  "experience.label": "WORK EXPERIENCE",
  "experience.title": "Experience shaped by real work.",
  "experience.intro": "Each role gave me a different kind of experience, but all of them shaped the same work ethic: understand the task quickly, follow the process correctly, and complete the work responsibly.",
  "experience.indomaret.role": "Store Crew",
  "experience.indomaret.period": "Feb 2025 - Feb 2026",
  "experience.indomaret.body": "Handled daily store activities from receiving goods and organizing stock to checking product conditions and processing cashier transactions. This role trained me to stay accurate with inventory and payments, adjust priorities quickly, and provide reliable service in a fast-moving work environment.",
  "experience.bmc.role": "Administrator",
  "experience.bmc.period": "Nov 2024 - Jan 2025",
  "experience.bmc.body": "Managed service documents, invoices, and transaction records while helping customers understand costs, service times, and spare-part availability. This role strengthened my ability to organize data, communicate clearly, and keep administrative work in order.",
  "experience.mitra.role": "Production Operator",
  "experience.mitra.period": "Jan 2023 - Aug 2024",
  "experience.mitra.body": "Worked according to briefings, standard procedures, and production quality requirements. I became accustomed to checking work carefully, maintaining a clean work area, and preparing accurate reports. This experience developed the discipline to work safely, consistently, and responsibly.",
  "experience.restu.role": "IT Support Intern",
  "experience.restu.period": "Nov 2021 - Feb 2022",
  "experience.restu.body": "Disassembled and reassembled laptop and PC components, upgraded hardware, and reinstalled operating systems and software. This hands-on experience became the foundation of my ability to understand devices, trace basic problems, and carry out technical work in a clear sequence.",
  "skills.label": "COMPETENCIES",
  "skills.title": "Skills built through practice.",
  "skills.intro": "These skills were developed through work I have handled directly, from supporting devices and production processes to managing data and serving customers.",
  "skills.technical.title": "Technical Support",
  "skills.technical.items": "Laptop and PC assembly or disassembly|Operating-system and software installation|Hardware upgrades|Basic device troubleshooting",
  "skills.operations.title": "Operations & Quality",
  "skills.operations.items": "Stamping-press operation|Work according to SOP|Production-quality checks|Work records and reports",
  "skills.admin.title": "Administration & Service",
  "skills.admin.items": "Service data and document management|Invoice creation and filing|Transaction recording|Customer communication and service",
  "skills.retail.title": "Retail & Inventory",
  "skills.retail.items": "Cashier and POS operation|Receiving and checking goods|FIFO/FEFO and stock management|Display, facing, and planogram",
  "education.label": "EDUCATION",
  "education.title": "Where the technical foundation began.",
  "education.institution": "Muhammadiyah 1 Vocational High School, Muntilan",
  "education.official": "Official institution name: SMK Muhammadiyah 1 Muntilan",
  "education.program": "Software Engineering",
  "education.period": "July 2019 to June 2022",
  "education.description": "Studying Software Engineering was where I first became familiar with computers and technology. I learned to understand problems in a structured way and solve them through clear steps. I later developed this foundation through practical experience as an IT Support intern.",
  "contact.label": "READY TO CONTRIBUTE",
  "contact.title": "Let’s Discuss the Next Opportunity.",
  "contact.description": "I am open to opportunities that match my experience and abilities. If my profile fits your company's needs, I would be glad to discuss the available role and responsibilities further.",
  "contact.emailAction": "Send Email",
  "contact.emailLabel": "Email",
  "contact.phoneLabel": "Phone",
  "contact.linkedinLabel": "LinkedIn",
  "contact.githubLabel": "GitHub",
  "contact.instagramLabel": "Instagram",
  "contact.facebookLabel": "Facebook",
  "contact.locationLabel": "Location",
  "preferences.language": "Language selection",
  "preferences.appearance": "Appearance selection",
  "preferences.id": "Indonesian language",
  "preferences.eng": "English language",
  "preferences.light": "Light mode",
  "preferences.dark": "Dark mode",
  "footer.role": "IT Support & Operations Specialist",
  "announce.id": "Page language changed to Indonesian.",
  "announce.en": "Page language changed to English.",
  "announce.light": "Light mode enabled.",
  "announce.dark": "Dark mode enabled.",
};

export const CONTENT = Object.freeze({ id: Object.freeze(id), en: Object.freeze(en) });

export const LINKS = Object.freeze({
  email: "mailto:bayuandk4@gmail.com",
  phone: "tel:+6287881820662",
  linkedin: "https://linkedin.com/in/bayu-andika2003/",
  github: "https://github.com/bayz-dik/V-Forge",
  instagram: "https://www.instagram.com/bayydka?igsh=eGtocG5pbTJjNGcz",
  facebook: "https://www.facebook.com/share/1dEpojdwUy/",
});
